package mobile.miet.alex.com.mietunofficial_v2.data.orioks.users;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

import mobile.miet.alex.com.mietunofficial_v2.data.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "USER_MODEL".
*/
public class UserModelDao extends AbstractDao<UserModel, Integer> {

    public static final String TABLENAME = "USER_MODEL";

    /**
     * Properties of entity UserModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Numst = new Property(0, int.class, "numst", true, "NUMST");
        public final static Property Week = new Property(1, Integer.class, "week", false, "WEEK");
        public final static Property FirstName = new Property(2, String.class, "firstName", false, "FIRST_NAME");
        public final static Property LastName = new Property(3, String.class, "lastName", false, "LAST_NAME");
        public final static Property LastlastName = new Property(4, String.class, "lastlastName", false, "LASTLAST_NAME");
        public final static Property Napr = new Property(5, String.class, "napr", false, "NAPR");
        public final static Property Sem = new Property(6, Integer.class, "sem", false, "SEM");
    }

    private DaoSession daoSession;


    public UserModelDao(DaoConfig config) {
        super(config);
    }
    
    public UserModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_MODEL\" (" + //
                "\"NUMST\" INTEGER PRIMARY KEY NOT NULL ," + // 0: numst
                "\"WEEK\" INTEGER," + // 1: week
                "\"FIRST_NAME\" TEXT," + // 2: firstName
                "\"LAST_NAME\" TEXT," + // 3: lastName
                "\"LASTLAST_NAME\" TEXT," + // 4: lastlastName
                "\"NAPR\" TEXT," + // 5: napr
                "\"SEM\" INTEGER);"); // 6: sem
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getNumst());
 
        Integer week = entity.getWeek();
        if (week != null) {
            stmt.bindLong(2, week);
        }
 
        String firstName = entity.getFirstName();
        if (firstName != null) {
            stmt.bindString(3, firstName);
        }
 
        String lastName = entity.getLastName();
        if (lastName != null) {
            stmt.bindString(4, lastName);
        }
 
        String lastlastName = entity.getLastlastName();
        if (lastlastName != null) {
            stmt.bindString(5, lastlastName);
        }
 
        String napr = entity.getNapr();
        if (napr != null) {
            stmt.bindString(6, napr);
        }
 
        Integer sem = entity.getSem();
        if (sem != null) {
            stmt.bindLong(7, sem);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getNumst());
 
        Integer week = entity.getWeek();
        if (week != null) {
            stmt.bindLong(2, week);
        }
 
        String firstName = entity.getFirstName();
        if (firstName != null) {
            stmt.bindString(3, firstName);
        }
 
        String lastName = entity.getLastName();
        if (lastName != null) {
            stmt.bindString(4, lastName);
        }
 
        String lastlastName = entity.getLastlastName();
        if (lastlastName != null) {
            stmt.bindString(5, lastlastName);
        }
 
        String napr = entity.getNapr();
        if (napr != null) {
            stmt.bindString(6, napr);
        }
 
        Integer sem = entity.getSem();
        if (sem != null) {
            stmt.bindLong(7, sem);
        }
    }

    @Override
    protected final void attachEntity(UserModel entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    @Override
    public UserModel readEntity(Cursor cursor, int offset) {
        UserModel entity = new UserModel( //
            cursor.getInt(offset + 0), // numst
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // week
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // firstName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // lastName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // lastlastName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // napr
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6) // sem
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserModel entity, int offset) {
        entity.setNumst(cursor.getInt(offset + 0));
        entity.setWeek(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setFirstName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLastName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLastlastName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setNapr(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSem(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(UserModel entity, long rowId) {
        return entity.getNumst();
    }
    
    @Override
    public Integer getKey(UserModel entity) {
        if(entity != null) {
            return entity.getNumst();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserModel entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
