package mobile.miet.alex.com.mietunofficial_v2.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "EVENT_MODEL".
*/
public class EventModelDao extends AbstractDao<EventModel, String> {

    public static final String TABLENAME = "EVENT_MODEL";

    /**
     * Properties of entity EventModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property IdDis = new Property(0, String.class, "idDis", true, "ID_DIS");
        public final static Property Itog_name = new Property(1, String.class, "itog_name", false, "ITOG_NAME");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Ball = new Property(3, String.class, "ball", false, "BALL");
        public final static Property Min_ball = new Property(4, String.class, "min_ball", false, "MIN_BALL");
        public final static Property Max_ball = new Property(5, String.class, "max_ball", false, "MAX_BALL");
        public final static Property Mark = new Property(6, String.class, "mark", false, "MARK");
        public final static Property Sh = new Property(7, String.class, "sh", false, "SH");
        public final static Property Week = new Property(8, Integer.class, "week", false, "WEEK");
        public final static Property IdLink = new Property(9, String.class, "idLink", false, "ID_LINK");
    }

    private Query<EventModel> disciplineModel_EventsQuery;

    public EventModelDao(DaoConfig config) {
        super(config);
    }
    
    public EventModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EVENT_MODEL\" (" + //
                "\"ID_DIS\" TEXT PRIMARY KEY NOT NULL ," + // 0: idDis
                "\"ITOG_NAME\" TEXT," + // 1: itog_name
                "\"NAME\" TEXT," + // 2: name
                "\"BALL\" TEXT," + // 3: ball
                "\"MIN_BALL\" TEXT," + // 4: min_ball
                "\"MAX_BALL\" TEXT," + // 5: max_ball
                "\"MARK\" TEXT," + // 6: mark
                "\"SH\" TEXT," + // 7: sh
                "\"WEEK\" INTEGER," + // 8: week
                "\"ID_LINK\" TEXT NOT NULL );"); // 9: idLink
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EVENT_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EventModel entity) {
        stmt.clearBindings();
 
        String idDis = entity.getIdDis();
        if (idDis != null) {
            stmt.bindString(1, idDis);
        }
 
        String itog_name = entity.getItog_name();
        if (itog_name != null) {
            stmt.bindString(2, itog_name);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String ball = entity.getBall();
        if (ball != null) {
            stmt.bindString(4, ball);
        }
 
        String min_ball = entity.getMin_ball();
        if (min_ball != null) {
            stmt.bindString(5, min_ball);
        }
 
        String max_ball = entity.getMax_ball();
        if (max_ball != null) {
            stmt.bindString(6, max_ball);
        }
 
        String mark = entity.getMark();
        if (mark != null) {
            stmt.bindString(7, mark);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(8, sh);
        }
 
        Integer week = entity.getWeek();
        if (week != null) {
            stmt.bindLong(9, week);
        }
        stmt.bindString(10, entity.getIdLink());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EventModel entity) {
        stmt.clearBindings();
 
        String idDis = entity.getIdDis();
        if (idDis != null) {
            stmt.bindString(1, idDis);
        }
 
        String itog_name = entity.getItog_name();
        if (itog_name != null) {
            stmt.bindString(2, itog_name);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String ball = entity.getBall();
        if (ball != null) {
            stmt.bindString(4, ball);
        }
 
        String min_ball = entity.getMin_ball();
        if (min_ball != null) {
            stmt.bindString(5, min_ball);
        }
 
        String max_ball = entity.getMax_ball();
        if (max_ball != null) {
            stmt.bindString(6, max_ball);
        }
 
        String mark = entity.getMark();
        if (mark != null) {
            stmt.bindString(7, mark);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(8, sh);
        }
 
        Integer week = entity.getWeek();
        if (week != null) {
            stmt.bindLong(9, week);
        }
        stmt.bindString(10, entity.getIdLink());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public EventModel readEntity(Cursor cursor, int offset) {
        EventModel entity = new EventModel( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // idDis
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // itog_name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ball
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // min_ball
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // max_ball
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // mark
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // sh
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // week
            cursor.getString(offset + 9) // idLink
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EventModel entity, int offset) {
        entity.setIdDis(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setItog_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBall(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMin_ball(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMax_ball(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMark(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSh(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setWeek(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setIdLink(cursor.getString(offset + 9));
     }
    
    @Override
    protected final String updateKeyAfterInsert(EventModel entity, long rowId) {
        return entity.getIdDis();
    }
    
    @Override
    public String getKey(EventModel entity) {
        if(entity != null) {
            return entity.getIdDis();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EventModel entity) {
        return entity.getIdDis() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "events" to-many relationship of DisciplineModel. */
    public List<EventModel> _queryDisciplineModel_Events(String idLink) {
        synchronized (this) {
            if (disciplineModel_EventsQuery == null) {
                QueryBuilder<EventModel> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdLink.eq(null));
                disciplineModel_EventsQuery = queryBuilder.build();
            }
        }
        Query<EventModel> query = disciplineModel_EventsQuery.forCurrentThread();
        query.setParameter(0, idLink);
        return query.list();
    }

}
