package mobile.miet.alex.com.mietunofficial_v2.greenDao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "EVENT_MODEL".
 */
@Entity
public class EventModel implements Serializable {

    @Id
    private String idDis;
    private String itog_name;
    private String name;
    private String ball;
    private String min_ball;
    private String max_ball;
    private String mark;
    private String sh;
    private Integer week;

    @NotNull
    private String idLink;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public EventModel() {
    }

    public EventModel(String idDis) {
        this.idDis = idDis;
    }

    @Generated
    public EventModel(String idDis, String itog_name, String name, String ball, String min_ball, String max_ball, String mark, String sh, Integer week, String idLink) {
        this.idDis = idDis;
        this.itog_name = itog_name;
        this.name = name;
        this.ball = ball;
        this.min_ball = min_ball;
        this.max_ball = max_ball;
        this.mark = mark;
        this.sh = sh;
        this.week = week;
        this.idLink = idLink;
    }

    public String getIdDis() {
        return idDis;
    }

    public void setIdDis(String idDis) {
        this.idDis = idDis;
    }

    public String getItog_name() {
        return itog_name;
    }

    public void setItog_name(String itog_name) {
        this.itog_name = itog_name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBall() {
        return ball;
    }

    public void setBall(String ball) {
        this.ball = ball;
    }

    public String getMin_ball() {
        return min_ball;
    }

    public void setMin_ball(String min_ball) {
        this.min_ball = min_ball;
    }

    public String getMax_ball() {
        return max_ball;
    }

    public void setMax_ball(String max_ball) {
        this.max_ball = max_ball;
    }

    public String getMark() {
        return mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

    public String getSh() {
        return sh;
    }

    public void setSh(String sh) {
        this.sh = sh;
    }

    public Integer getWeek() {
        return week;
    }

    public void setWeek(Integer week) {
        this.week = week;
    }

    @NotNull
    public String getIdLink() {
        return idLink;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdLink(@NotNull String idLink) {
        this.idLink = idLink;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
