package mobile.miet.alex.com.mietunofficial_v2.greenDao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "LESSON_MODEL".
 */
@Entity
public class LessonModel implements java.io.Serializable {

    @Id
    private Long id;
    private Integer week;
    private String day;
    private String room;
    private String time;
    private String timeFrom;
    private String timeTo;
    private String code;
    private boolean week1;
    private boolean week2;
    private boolean week3;
    private boolean week4;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public LessonModel() {
    }

    public LessonModel(Long id) {
        this.id = id;
    }

    @Generated
    public LessonModel(Long id, Integer week, String day, String room, String time, String timeFrom, String timeTo, String code, boolean week1, boolean week2, boolean week3, boolean week4) {
        this.id = id;
        this.week = week;
        this.day = day;
        this.room = room;
        this.time = time;
        this.timeFrom = timeFrom;
        this.timeTo = timeTo;
        this.code = code;
        this.week1 = week1;
        this.week2 = week2;
        this.week3 = week3;
        this.week4 = week4;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getWeek() {
        return week;
    }

    public void setWeek(Integer week) {
        this.week = week;
    }

    public String getDay() {
        return day;
    }

    public void setDay(String day) {
        this.day = day;
    }

    public String getRoom() {
        return room;
    }

    public void setRoom(String room) {
        this.room = room;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getTimeFrom() {
        return timeFrom;
    }

    public void setTimeFrom(String timeFrom) {
        this.timeFrom = timeFrom;
    }

    public String getTimeTo() {
        return timeTo;
    }

    public void setTimeTo(String timeTo) {
        this.timeTo = timeTo;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public boolean getWeek1() {
        return week1;
    }

    public void setWeek1(boolean week1) {
        this.week1 = week1;
    }

    public boolean getWeek2() {
        return week2;
    }

    public void setWeek2(boolean week2) {
        this.week2 = week2;
    }

    public boolean getWeek3() {
        return week3;
    }

    public void setWeek3(boolean week3) {
        this.week3 = week3;
    }

    public boolean getWeek4() {
        return week4;
    }

    public void setWeek4(boolean week4) {
        this.week4 = week4;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
