package mobile.miet.alex.com.mietunofficial_v2.greenDao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "LESSON_MODEL".
 */
@Entity
public class LessonModel implements java.io.Serializable {
    private Integer week;
    private Integer day;
    private String room;
    private String time;
    private String timeFrom;
    private String timeTo;
    private String code;

    @NotNull
    private String groupName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public LessonModel() {
    }

    @Generated
    public LessonModel(Integer week, Integer day, String room, String time, String timeFrom, String timeTo, String code, String groupName) {
        this.week = week;
        this.day = day;
        this.room = room;
        this.time = time;
        this.timeFrom = timeFrom;
        this.timeTo = timeTo;
        this.code = code;
        this.groupName = groupName;
    }

    public Integer getWeek() {
        return week;
    }

    public void setWeek(Integer week) {
        this.week = week;
    }

    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }

    public String getRoom() {
        return room;
    }

    public void setRoom(String room) {
        this.room = room;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getTimeFrom() {
        return timeFrom;
    }

    public void setTimeFrom(String timeFrom) {
        this.timeFrom = timeFrom;
    }

    public String getTimeTo() {
        return timeTo;
    }

    public void setTimeTo(String timeTo) {
        this.timeTo = timeTo;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @NotNull
    public String getGroupName() {
        return groupName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGroupName(@NotNull String groupName) {
        this.groupName = groupName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
