package mobile.miet.alex.com.mietunofficial_v2.greenDao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "USER_MODEL".
 */
@Entity
public class UserModel implements java.io.Serializable {
    private String numst;
    private String week;
    private String firstname;
    private String lastname;
    private String lastlastname;
    private String napr;
    private String sem;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public UserModel() {
    }

    @Generated
    public UserModel(String numst, String week, String firstname, String lastname, String lastlastname, String napr, String sem) {
        this.numst = numst;
        this.week = week;
        this.firstname = firstname;
        this.lastname = lastname;
        this.lastlastname = lastlastname;
        this.napr = napr;
        this.sem = sem;
    }

    public String getNumst() {
        return numst;
    }

    public void setNumst(String numst) {
        this.numst = numst;
    }

    public String getWeek() {
        return week;
    }

    public void setWeek(String week) {
        this.week = week;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getLastlastname() {
        return lastlastname;
    }

    public void setLastlastname(String lastlastname) {
        this.lastlastname = lastlastname;
    }

    public String getNapr() {
        return napr;
    }

    public void setNapr(String napr) {
        this.napr = napr;
    }

    public String getSem() {
        return sem;
    }

    public void setSem(String sem) {
        this.sem = sem;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
